[build]
     publish = "public"
     functions = "functions"

[[redirects]]
from = "/app"
to = "/.netlify/functions/check-auth"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
